plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.chaquopy)
}

android {
    namespace = "com.montessoricopilot.app"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.montessoricopilot.app"
        // Chaquopy requires minSdk >= 24; 26 keeps us on a modern, well-supported
        // baseline (Android 8.0+) while comfortably clearing that floor.
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "0.2.0"

        // Chaquopy needs to know which ABIs to bundle a Python interpreter for.
        // Start with the two that cover the vast majority of real devices;
        // add x86_64 if you also want emulator support without an ARM image.
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a")
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }

    // content_seed.json is generated by tools/generate_content_seed.py and
    // checked in under src/main/assets — ContentDatabase reads it once, on
    // first launch, to populate the (Room-created) content database.
    sourceSets {
        getByName("main") {
            assets.srcDirs("src/main/assets")
        }
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

chaquopy {
    defaultConfig {
        // Keep in sync with the interpreter version Chaquopy ships for this
        // plugin release; see https://chaquo.com/chaquopy/doc/current/versions.html
        version = "3.12"
        // No third-party pip packages yet — the logic layer (src/main/python)
        // is deliberately dependency-free stdlib Python so it stays small and
        // easy to unit-test. Add `pip { install(...) }` here if that changes.
    }
}

dependencies {
    implementation(libs.core.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.viewmodel.compose)
    implementation(libs.activity.compose)
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    // Pulls in the full Material icon set (Book, Inventory2, etc.) beyond
    // the small default set — fine at this project's size; if APK size
    // becomes a concern later, switch to per-icon artifacts.
    implementation(libs.compose.material.icons.extended)
    implementation(libs.navigation.compose)
    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler)
    implementation(libs.work.runtime.ktx)
    implementation(libs.kotlinx.serialization.json)

    debugImplementation(libs.compose.ui.tooling)

    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.6.1")
}
