plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.chaquopy)
}

android {
    namespace = "com.montessoricopilot.app"
    // API 36 (Android 16). Google Play requires new apps and updates to
    // target API 36 as of 31 Aug 2026, so 35 would not be publishable.
    // compileSdk 36 requires AGP >= 8.9.1 (pinned in libs.versions.toml).
    compileSdk = 36

    defaultConfig {
        applicationId = "com.montessoricopilot.app"
        // Chaquopy requires minSdk >= 24; 26 keeps us on a modern, well-supported
        // baseline (Android 8.0+) while comfortably clearing that floor.
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = "0.2.0"

        // Chaquopy needs to know which ABIs to bundle a Python interpreter for.
        // arm64-v8a  = every modern physical Android device (Play has required
        //              64-bit since 2019; 32-bit armeabi-v7a is legacy and
        //              Chaquopy's Python 3.12 is not built for it at all).
        // x86_64     = the Android emulator on an Intel Mac / PC.
        // Each ABI adds its own copy of the Python interpreter to the APK, so
        // don't add more than you actually ship. An Apple-silicon Mac's
        // emulator uses arm64-v8a and is already covered.
        ndk {
            abiFilters += listOf("arm64-v8a", "x86_64")
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }

    // content_seed.json is generated by tools/generate_content_seed.py and
    // checked in under src/main/assets — ContentDatabase reads it once, on
    // first launch, to populate the (Room-created) content database.
    sourceSets {
        getByName("main") {
            assets.srcDirs("src/main/assets")
        }
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

// Both databases set exportSchema = true, which makes Room write a JSON
// snapshot of each schema version here. Those snapshots are what let you
// write real migration tests later (and diff what changed between versions),
// so this directory is worth committing to git.
ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
}

chaquopy {
    defaultConfig {
        // Keep in sync with the interpreter version Chaquopy ships for this
        // plugin release; see https://chaquo.com/chaquopy/doc/current/versions.html
        version = "3.12"
        // No third-party pip packages yet — the logic layer (src/main/python)
        // is deliberately dependency-free stdlib Python so it stays small and
        // easy to unit-test. Add `pip { install(...) }` here if that changes.
    }
}

dependencies {
    implementation(libs.core.ktx)
    implementation(libs.lifecycle.runtime.ktx)
    implementation(libs.lifecycle.viewmodel.compose)
    implementation(libs.activity.compose)
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    // Pulls in the full Material icon set (Book, Inventory2, etc.) beyond
    // the small default set — fine at this project's size; if APK size
    // becomes a concern later, switch to per-icon artifacts.
    implementation(libs.compose.material.icons.extended)
    implementation(libs.navigation.compose)
    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler)
    implementation(libs.work.runtime.ktx)
    implementation(libs.kotlinx.serialization.json)

    debugImplementation(libs.compose.ui.tooling)

    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.6.1")
}
